export const ACTION_STATE = 'ACTION_STATE';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const SIGNUP_PENDING = 'SIGNUP_PENDING';
export const SIGNUP_FULFILLED = 'SIGNUP_FULFILLED';
export const SIGNUP_REJECTED = 'SIGNUP_REJECTED';


export const GET_ALL_PRODUCTS_PENDING = 'GET_ALL_PRODUCTS_PENDING';
export const GET_ALL_PRODUCTS_FULFILLED = 'GET_ALL_PRODUCTS_FULFILLED';
export const GET_ALL_PRODUCTS_REJECTED = 'GET_ALL_PRODUCTS_REJECTED';


export const GET_ALL_CART_PRODUCTS_PENDING = 'GET_ALL_CART_PRODUCTS_PENDING';
export const GET_ALL_CART_PRODUCTS_FULFILLED = 'GET_AL_CARTL_PRODUCTS_FULFILLED';
export const GET_ALL_CART_PRODUCTS_REJECTED = 'GET_ALL_CART_PRODUCTS_REJECTED';

export const ADD_CART_PRODUCTS_PENDING = 'ADD_CART_PRODUCTS_PENDING';
export const ADD_CART_PRODUCTS_FULFILLED = 'ADD_CART_PRODUCTS_FULFILLED';
export const ADD_CART_PRODUCTS_REJECTED = 'ADD_CART_PRODUCTS_REJECTED';
